// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAd-cgn1a9b9eNqDpE2Rt2WFkgPqD5S1E',
    appId: '1:748022951650:web:59e2b81251dafb4c0878bb',
    messagingSenderId: '748022951650',
    projectId: 'test-b1b24',
    authDomain: 'test-b1b24.firebaseapp.com',
    storageBucket: 'test-b1b24.appspot.com',
    measurementId: 'G-VRD2ZVQQSY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQSFHZvs5Lo333ft3VOBGFqxFGouSwJeA',
    appId: '1:748022951650:android:ffe1ed1016f697450878bb',
    messagingSenderId: '748022951650',
    projectId: 'test-b1b24',
    storageBucket: 'test-b1b24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChMziiiUiWCi9uyl5MZYSvVJnAZCCQc3c',
    appId: '1:748022951650:ios:7eb3b5da2aa4a3fc0878bb',
    messagingSenderId: '748022951650',
    projectId: 'test-b1b24',
    storageBucket: 'test-b1b24.appspot.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChMziiiUiWCi9uyl5MZYSvVJnAZCCQc3c',
    appId: '1:748022951650:ios:8f3f0eb8a0f3586d0878bb',
    messagingSenderId: '748022951650',
    projectId: 'test-b1b24',
    storageBucket: 'test-b1b24.appspot.com',
    iosBundleId: 'com.example.test.RunnerTests',
  );
}
